apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          envFrom:
            - configMapRef:
                name: dev-db-config
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: "/var/lib/mongo"
              name: mongo-pv
      volumes:
        - name: mongo-pv
          persistentVolumeClaim:
            claimName: mongo-pvc
      restartPolicy: Always
status: {}
