apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: poc
  name: poc
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: poc
    spec:
      containers:
        - image: amartlop/poc:latest
          name: poc
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}