apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc
spec:
  replicas: 10
  selector:
    matchLabels:
      app: poc
  template:
    metadata:
      labels:
        app: poc
    spec:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 9
          maxSurge: 1
      containers:
        - image: amartlop/poc:latest
          name: poc
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: poc-config
            - configMapRef:
                name: poc-common-config