apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poc
  template:
    metadata:
      labels:
        app: poc
    spec:
      containers:
        - image: amartlop/poc:latest
          name: poc
          ports:
            - containerPort: 3000